In [1]:
import numpy as np

In [2]:
#1. single dimensional array: array inbuilt function of array
#array([]): single dimensional array
#array([[],[],[]]): two dimensional array

In [3]:
#how to crate the single dimensional array
a=np.array([40,60,80,90,75])

In [4]:
print(a)

[40 60 80 90 75]


In [5]:
#To check type of a
print(type(a))

<class 'numpy.ndarray'>


In [6]:
#shape
a.shape #row,col here 5 rows and 1 column means(5,)

(5,)

In [7]:
#ndim: to show dimensional
a.ndim

1

In [8]:
#dtype inbuilt method , to show datatype of array variable
a.dtype

dtype('int32')

In [9]:
a.size #size inbuilt method, to show no of element in array variable

5

In [10]:
a.itemsize #to occupy the memory of each elemt of array varable of a

4

In [11]:
 #To occupy total memory space by array a and unit in bytes 
# formula apply: total no of bytes=size of array*itemsize of each element of the array
a.size*a.itemsize

20

In [12]:
a.nbytes #nbytes inbuilt method: represent the total no of bytes occupyed of an array

20

In [13]:
#Attribute of numpy array
#1. ndim 2. shape 3. dtype 4. size 5. itemsize 6. nbytes

In [14]:
#Access data from single dimensional array
#there are two types of access data from numpy array:
#1. Indexing method 2. Slicing method


In [15]:
#1. Indexing method
print(a)

[40 60 80 90 75]


In [16]:
print(a[1])

60


In [17]:
print(a[-3])

80


In [18]:
# 2. Slicing method
#access data throught slicing: from:to means start:stop

In [19]:
#access data from 1st position to 3rd position 
print(a[1:4])

[60 80 90]


In [20]:
print(a[2:]) #access data from 2nd location to till end

[80 90 75]


In [21]:
print(a)

[40 60 80 90 75]


In [22]:
#to sum of element of array a
a.sum()

345

In [23]:
#to find the maximum array of a
a.max()

90

In [24]:
a.min()

40

In [25]:
a.mean() #to find the average of array(40+60+80+90+75)/5

69.0

In [26]:
#another meathod for create a single dimensional array
#use(start,stop,step)
x=np.arange(10,21)

In [27]:
print(x)

[10 11 12 13 14 15 16 17 18 19 20]


In [28]:
y=np.arange(100,150,2)

In [29]:
print(y)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148]


In [30]:
z=np.arange(10) #10 means stop means start 0 if no mention and step=1 if no mention stop 10-1=9
print(z)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
x=np.arange(10,0,-1)

In [32]:
print(x)

[10  9  8  7  6  5  4  3  2  1]


In [33]:
a=np.array([10,20,30,40,50],float)

In [34]:
print(a)

[10. 20. 30. 40. 50.]


In [35]:
a.dtype

dtype('float64')

In [36]:
a[2]=30.5 #update value of 2nd position with 30.5

In [37]:
print(a)

[10.  20.  30.5 40.  50. ]


In [38]:
a=np.zeros(10) #bydefault type float

In [39]:
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [40]:
a[1]=67

In [41]:
print(a)

[ 0. 67.  0.  0.  0.  0.  0.  0.  0.  0.]


In [42]:
a=np.zeros(10,int)

In [43]:
print(a)

[0 0 0 0 0 0 0 0 0 0]


In [44]:
a[3]=89.5

In [45]:
print(a)

[ 0  0  0 89  0  0  0  0  0  0]


In [46]:
a=np.ones(8) #bydefault float

In [47]:
print(a)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [48]:
#To create two dimensional array
a=np.array([[10,20,30,40],[50,90,70,80],[70,90,40,10],[30,60,40,80]])

In [49]:
print(a)

[[10 20 30 40]
 [50 90 70 80]
 [70 90 40 10]
 [30 60 40 80]]


In [50]:
a.ndim

2

In [51]:
a.shape

(4, 4)

In [52]:
a.size

16

In [53]:
a.itemsize

4

In [54]:
a.dtype

dtype('int32')

In [55]:
a.nbytes

64

In [56]:
print(a)

[[10 20 30 40]
 [50 90 70 80]
 [70 90 40 10]
 [30 60 40 80]]


In [57]:
# There are 2 types of method to retrive data from 2D numpy array
#1. Indexing and 2. Slicing

In [58]:
#1. indexing
# access data from 1st row
print(a[1,])


[50 90 70 80]


In [62]:
#access data from 2nd column (all rows of 2nd column)
print(a[:,2]) # row, col [start:end,column]

[30 70 40 40]


In [61]:
# access data from 3rd column of 2nd row
print(a[2,3])

10


In [63]:
print(a[-1,-3])

60


In [64]:
print(a)

[[10 20 30 40]
 [50 90 70 80]
 [70 90 40 10]
 [30 60 40 80]]


In [65]:
# sum of all elements of 2D array
a.sum()

810

In [66]:
#sum row wise (Horizontally) axis=1
a.sum(axis=1)

array([100, 290, 210, 210])

In [68]:
#sum column wise (Vertically) axis=1
a.sum(axis=0)

array([160, 260, 180, 210])

In [69]:
#sum row wise (Horizontally) axis=1
a.mean(axis=1)

array([25. , 72.5, 52.5, 52.5])

In [70]:
#sum column wise (Vertically) axis=1
a.mean(axis=0)

array([40. , 65. , 45. , 52.5])

In [71]:
#max(), min()

In [72]:
#Arithmetic operation
#Find the sum of 2 single dimensional array
a=np.array([10,20,30,40])
b=np.array([30,40,50,60])

In [73]:
print(a)

[10 20 30 40]


In [74]:
print(b)

[30 40 50 60]


In [75]:
a+b

array([ 40,  60,  80, 100])

In [76]:
#reshape() : to converts single dimensional array to two dimensional array
#for eg.
a=np.arange(8) # here mension stop=8 means 8-1=7 and start=0 end stop-1 step=+1
print(a)

[0 1 2 3 4 5 6 7]


In [77]:
#convert array a into 2D array 4*2=total 8 elements means 4 rows and 2 col
b=a.reshape(4,2)
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [78]:
a.ndim

1

In [80]:
b.ndim

2

In [81]:
#Trigometric function
# sin(), cos(), tan()
#find 30 degree
#30 ==>value
#value*pi/180 here pi=3.14


In [86]:
#find sin30 degree
y=np.sin(30*3.14/180)
print(y)
#round
y=np.round(y,1)
print(y)

0.4997701026431024
0.5


In [87]:
 #find cos30 degree
y=np.cos(30*3.14/180)
print(y)
#round
y=np.round(y,1)
print(y)

0.866158094405463
0.9
