# Regularisation

In [1]:
#Dataset use automobile_data.csv

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [3]:
df=pd.read_csv("Automobile_data.csv")

In [4]:
df.head()

symboling normalized-losses         make fuel-type   body-style  \
0          3                 ?  alfa-romero       gas  convertible   
1          3                 ?  alfa-romero       gas  convertible   
2          1                 ?  alfa-romero       gas    hatchback   
3          2               164         audi       gas        sedan   
4          2               164         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

  horsepower  city-mpg  highway-mpg  price  
0        111        21           27  13495  
1        111        21           27  16500  
2        154        19           26  16500  
3        102        24           30  13950  
4        115        18           22  17450

In [5]:
#check null value
df.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    object 
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   body-style         205 non-null    object 
 5   drive-wheels       205 non-null    object 
 6   engine-location    205 non-null    object 
 7   width              205 non-null    float64
 8   height             205 non-null    float64
 9   engine-type        205 non-null    object 
 10  engine-size        205 non-null    int64  
 11  horsepower         205 non-null    object 
 12  city-mpg           205 non-null    int64  
 13  highway-mpg        205 non-null    int64  
 14  price              205 non-null    int64  
dtypes: float64(2), int64(5), object(8)
memory usage: 24.1+ KB


In [7]:
df["normalized-losses"].unique()

array(['?', '164', '158', '192', '188', '121', '98', '81', '118', '148',
       '110', '145', '137', '101', '78', '106', '85', '107', '104', '113',
       '150', '129', '115', '93', '142', '161', '153', '125', '128',
       '122', '103', '168', '108', '194', '231', '119', '154', '74',
       '186', '83', '102', '89', '87', '77', '91', '134', '65', '197',
       '90', '94', '256', '95'], dtype=object)

In [8]:
df["normalized-losses"].value_counts()

?      41
161    11
91      8
150     7
104     6
134     6
128     6
94      5
168     5
95      5
102     5
103     5
65      5
74      5
85      5
93      4
148     4
118     4
122     4
106     4
125     3
115     3
137     3
83      3
101     3
154     3
87      2
153     2
81      2
192     2
164     2
188     2
197     2
158     2
194     2
110     2
89      2
108     2
113     2
145     2
119     2
129     2
186     1
142     1
121     1
78      1
231     1
256     1
107     1
98      1
90      1
77      1
Name: normalized-losses, dtype: int64

In [9]:
#Cleaning Data

In [10]:
df["normalized-losses"].replace("?",np.nan,inplace=True)
#type change permanently
df["normalized-losses"]=df["normalized-losses"].astype("float")
df["normalized-losses"].fillna(df["normalized-losses"].mean(),inplace=True)

In [11]:
df["horsepower"].replace("?",np.nan,inplace=True)
#type change permanently
df["horsepower"]=df["horsepower"].astype("float")
df["horsepower"].fillna(df["horsepower"].mean(),inplace=True)

In [12]:
#To sepeate Numerical type and categorical type variable
df_num=df.select_dtypes(["int64","float64"])
df_cat=df.select_dtypes(object)

In [13]:
df_cat.columns

Index(['make', 'fuel-type', 'body-style', 'drive-wheels', 'engine-location',
       'engine-type'],
      dtype='object')

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
for col in df_cat:
    le=LabelEncoder()
    df_cat[col]=le.fit_transform(df_cat[col])

In [16]:
df_cat.head()

make  fuel-type  body-style  drive-wheels  engine-location  engine-type
0     0          1           0             2                0            0
1     0          1           0             2                0            0
2     0          1           2             2                0            5
3     1          1           3             1                0            3
4     1          1           3             0                0            3

In [17]:
#To merge means concatenate of numerical and categorical data set
df_new=pd.concat([df_num,df_cat],axis=1)

In [18]:
df_new

symboling  normalized-losses  width  height  engine-size  horsepower  \
0            3              122.0   64.1    48.8          130       111.0   
1            3              122.0   64.1    48.8          130       111.0   
2            1              122.0   65.5    52.4          152       154.0   
3            2              164.0   66.2    54.3          109       102.0   
4            2              164.0   66.4    54.3          136       115.0   
..         ...                ...    ...     ...          ...         ...   
200         -1               95.0   68.9    55.5          141       114.0   
201         -1               95.0   68.8    55.5          141       160.0   
202         -1               95.0   68.9    55.5          173       134.0   
203         -1               95.0   68.9    55.5          145       106.0   
204         -1               95.0   68.9    55.5          141       114.0   

     city-mpg  highway-mpg  price  make  fuel-type  body-style  drive-wheels  \
0          21           27  13495     0          1           0             2   
1          21           27  16500     0          1           0             2   
2          19           26  16500     0          1           2             2   
3          24           30  13950     1          1           3             1   
4          18           22  17450     1          1           3             0   
..        ...          ...    ...   ...        ...         ...           ...   
200        23           28  16845    21          1           3             2   
201        19           25  19045    21          1           3             2   
202        18           23  21485    21          1           3             2   
203        26           27  22470    21          0           3             2   
204        19           25  22625    21          1           3             2   

     engine-location  engine-type  
0                  0            0  
1                  0            0  
2                  0            5  
3                  0            3  
4                  0            3  
..               ...          ...  
200                0            3  
201                0            3  
202                0            5  
203                0            3  
204                0            3  

[205 rows x 15 columns]

In [19]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    float64
 2   width              205 non-null    float64
 3   height             205 non-null    float64
 4   engine-size        205 non-null    int64  
 5   horsepower         205 non-null    float64
 6   city-mpg           205 non-null    int64  
 7   highway-mpg        205 non-null    int64  
 8   price              205 non-null    int64  
 9   make               205 non-null    int32  
 10  fuel-type          205 non-null    int32  
 11  body-style         205 non-null    int32  
 12  drive-wheels       205 non-null    int32  
 13  engine-location    205 non-null    int32  
 14  engine-type        205 non-null    int32  
dtypes: float64(4), int32(6), int64(5)
memory usage: 19.3 KB


# BaseLine Model (Linear Regression)

In [20]:
#select X(input) and Y(target/output)
X=df_new.drop("price",axis=1)  # independent features
Y=df_new["price"]  #target means dependent which is predict

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
#spilt data into training (70%) and testing (30%)
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=1)

In [23]:
from sklearn.linear_model import LinearRegression

In [24]:
#create object of LinearRegression class
lr=LinearRegression()

In [25]:
#train the model with LinearRegression
lr.fit(x_train,y_train)

LinearRegression()

In [26]:
#check score of training
#score() inbuilt function of LinearRegression class
#score() is similar work as r2-score
lr.score(x_train,y_train)

0.8504573774895472

In [27]:
#Testing
#check score of testing
lr.score(x_test,y_test)

0.796556678039738

In [28]:
#if score of training>score of testing means model is overfitting
#so apply regularisation to overcome the overfitting problem

In [29]:
#if score of training>score of testing means training error<testing error means testing
#error is very high than the training error that is model is overfit so to
#overome(reduce) the overfitting, use regularisation

In [30]:
'''
There are 2 types of regularisation
1. L1 means Lasso   RSS+[Lambda*sum(abs(coefficient))]
2. L2 means Ridge
'''

'\nThere are 2 types of regularisation\n1. L1 means Lasso   RSS+[Lambda*sum(abs(coefficient))]\n2. L2 means Ridge\n'

In [31]:
from sklearn.linear_model import Lasso

In [32]:
#create the object of Lasso class and passing value of Lambda
l1=Lasso(1000) #here Lambda means alpha=100 (range od Lambda : 200 to 1000)

In [33]:
#Train the model with Lasso Regularisation : use fit()
l1.fit(x_train,y_train)

Lasso(alpha=1000)

In [34]:
#check coefficient /slope of all input features(columns) before add error on
#training time means before apply Lasso
lr.coef_    #lr object of LinearRegression class

array([ 4.51384957e+01,  1.53127607e+00,  7.89452171e+02,  3.62663990e+02,
        9.83682875e+01, -1.08169245e+01,  3.08017854e+02, -4.17024371e+02,
       -2.00099087e+02, -6.22650015e+02, -1.70235175e+02,  1.86860719e+03,
        1.64133620e+04,  2.83174279e+02])

In [35]:
X.columns    #independent/input features to display all column

Index(['symboling', 'normalized-losses', 'width', 'height', 'engine-size',
       'horsepower', 'city-mpg', 'highway-mpg', 'make', 'fuel-type',
       'body-style', 'drive-wheels', 'engine-location', 'engine-type'],
      dtype='object')

In [36]:
#check coefficient / slope of all input features(columns) after add error 
#on training time means after apply Lasso

In [37]:
l1.coef_   #L1 is object of Lasso

array([   0.        ,    3.96310671,    0.        ,  276.93279232,
        135.34169218,   16.00129073,   -0.        , -113.03311963,
       -126.40695244,   -0.        ,   -0.        ,    0.        ,
          0.        ,    0.        ])

In [38]:
#Apply Ridge Regularisation

In [39]:
from sklearn.linear_model import Ridge #RSS+Lambda*sum(square(all coeff))

In [40]:
#create the object of Ridge class and passing value of Lambda(0.1-50)
l2=Ridge(10)  #here 10 = value of Lambda/alpha

In [41]:
#Train the model with Ridge Regularisation : use fit()
l2.fit(x_train,y_train)

Ridge(alpha=10)

In [42]:
lr.coef_    #lr object of LinearRegression class

array([ 4.51384957e+01,  1.53127607e+00,  7.89452171e+02,  3.62663990e+02,
        9.83682875e+01, -1.08169245e+01,  3.08017854e+02, -4.17024371e+02,
       -2.00099087e+02, -6.22650015e+02, -1.70235175e+02,  1.86860719e+03,
        1.64133620e+04,  2.83174279e+02])

In [43]:
X.columns

Index(['symboling', 'normalized-losses', 'width', 'height', 'engine-size',
       'horsepower', 'city-mpg', 'highway-mpg', 'make', 'fuel-type',
       'body-style', 'drive-wheels', 'engine-location', 'engine-type'],
      dtype='object')

In [44]:
l2.coef_   #L2 is object of Ridge

array([ 2.08658930e+02, -5.60173023e-01,  3.64420144e+02,  5.72916414e+02,
        1.04441215e+02,  2.21332730e+01,  2.11271281e+02, -2.72864381e+02,
       -1.86340249e+02, -9.06610516e+02, -6.30655861e+02,  1.56860422e+03,
        2.57047785e+03,  5.15948757e+02])

In [45]:
#my observation , Lasso is better than Ridge
#Lasso is very important for features selection

In [46]:
#How to select the right value of Lambda/alpha
#for Ridge, select the right value of Lambda/alpha 

In [47]:
for i in range(51):  #start=0 , stop=51-1=50, step=+1
    #create object of Ridge
    l2=Ridge(i)    #i=0 RSS+Lambda=[sum(sqr(all coeff))]
    #train the model
    l2.fit(x_train,y_train)
    #check score on testing time
    print("Value of Lambda/Alpha :",i,"Score =",l2.score(x_test,y_test))

Value of Lambda/Alpha : 0 Score = 0.7965566780397381
Value of Lambda/Alpha : 1 Score = 0.8074518758147273
Value of Lambda/Alpha : 2 Score = 0.8110292248150517
Value of Lambda/Alpha : 3 Score = 0.8126933383890036
Value of Lambda/Alpha : 4 Score = 0.81361486450293
Value of Lambda/Alpha : 5 Score = 0.8141745853539417
Value of Lambda/Alpha : 6 Score = 0.8145301242133356
Value of Lambda/Alpha : 7 Score = 0.8147582608502816
Value of Lambda/Alpha : 8 Score = 0.8149010602831954
Value of Lambda/Alpha : 9 Score = 0.814983694925305
Value of Lambda/Alpha : 10 Score = 0.815022286737653
Value of Lambda/Alpha : 11 Score = 0.8150277245431791
Value of Lambda/Alpha : 12 Score = 0.8150076788279419
Value of Lambda/Alpha : 13 Score = 0.8149677381788261
Value of Lambda/Alpha : 14 Score = 0.8149120868051174
Value of Lambda/Alpha : 15 Score = 0.8148439278252522
Value of Lambda/Alpha : 16 Score = 0.8147657584947391
Value of Lambda/Alpha : 17 Score = 0.8146795554128125
Value of Lambda/Alpha : 18 Score = 0.81458

In [ ]:
#For Lasso , select the right value of Lambda/Alpha

In [48]:
for i in range(200,1000,50):  #start=200, stop=1000-1=999, step=+50
    #create object of Lasso
    l1=Lasso(i) #i=200 , i=250 RSS+Lambda*[sum(abs(all coeff))]
    #train the model
    l1.fit(x_train,y_train)
    #check score on testing time
    print("Value of Lambda/Alpha : ",i,"Score = ",l1.score(x_test,y_test))

Value of Lambda/Alpha :  200 Score =  0.813920135802378
Value of Lambda/Alpha :  250 Score =  0.812421909078023
Value of Lambda/Alpha :  300 Score =  0.8085057299003376
Value of Lambda/Alpha :  350 Score =  0.8036053753129061
Value of Lambda/Alpha :  400 Score =  0.7977229768452244
Value of Lambda/Alpha :  450 Score =  0.7950465607641612
Value of Lambda/Alpha :  500 Score =  0.7946028204251038
Value of Lambda/Alpha :  550 Score =  0.7942485978551435
Value of Lambda/Alpha :  600 Score =  0.7938656404830354
Value of Lambda/Alpha :  650 Score =  0.7934536226456451
Value of Lambda/Alpha :  700 Score =  0.7930208714948073
Value of Lambda/Alpha :  750 Score =  0.7925637235065689
Value of Lambda/Alpha :  800 Score =  0.7920812896372945
Value of Lambda/Alpha :  850 Score =  0.7915726589657283
Value of Lambda/Alpha :  900 Score =  0.7910703319438239
Value of Lambda/Alpha :  950 Score =  0.7910205756985367


In [ ]:
#Lasso : Lambda/alpha =200 and score =0.81
#Ridge : Lambda/alpha =2 and score =0.81

In [ ]:
#Cross Validation : call cross_val_score

In [49]:
from sklearn.model_selection import cross_val_score

In [ ]:
#Apply cross validation in Ridge Regularisation 

In [50]:
#create object of Ridge Regularisation
l1=Ridge(2)  #pass Lambda=2
#L1 user defined object of Ridge

In [51]:
#create object of cross_val_score
l1_cross=cross_val_score(l1,X,Y,cv=4)  
#CV inbuilt parameter : how many divide the dataset into no of fold/part

In [52]:
l1_cross

array([0.71176474, 0.86474228, 0.37640664, 0.47020196])

In [53]:
#find the average of all score(Ridge)
np.mean(l1_cross)

0.6057789059244749

In [ ]:
#Apply cross validation in Lasso Regularisation

In [54]:
#create object of Lasso Regularisation
l2=Lasso(200)  #pass Lambda=200
#L2 user defined object of Lasso

In [55]:
#create object of cross_val_score
l2_cross=cross_val_score(l2,X,Y,cv=4)
# CV inbuilt p[arameter : how many divide the dataset into no of fold/part

In [56]:
l2_cross

array([0.76560829, 0.81872367, 0.43344753, 0.448364  ])

In [57]:
#find the average of all score(Lasso)
np.mean(l2_cross)

0.6165358705430694

In [ ]:
#Average score of Lasso is greater then Ridge so Lasso Regularisation is best
#in this dataset Automobile_data.csv